Fix #26 & #12: report line and column numbers on left of code and visually differentiate them
Duhemm/sbt-errors-summary pull request #27
Opened 2017-07-23 04:05 UTC by yawaramin

The string manipulation logic should be good, but I've never developed or tested an sbt plugin before, so would appreciate some help with the testing.

2017-07-23 08:21 UTC, Duhemm requested changes
Thanks! The new errors are certainly much clearer 👏🏻

To run the tests, you first need to run `setupTests` in sbt. Then, you can run the tests for Scala 2.10 with `test2106:test`, for 2.11 with `test21111:test` and 2.12 with `test2122:test`. Just look at what `.travis.yml` does 😉 

I don't think that you'll need to modify the `test-api` or `test-compiler` projects. If you do, you'll need to run `clean` and `setupTests` again.

Let me know if I can help and thanks again 🎉!

2017-07-23 08:21 UTC, Duhemm commented on src/main/contraband-scala/sbt/errorssummary/ReporterConfig.scala
>  }
Is this you IDE formatting the code? Could you revert this change please? This code gets generated, and I format it with Scalafmt.

2017-07-23 08:21 UTC, Duhemm commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +    logger.info("En: error number n")
That'll make things much clearer. I have 2 suggestions:
 - Could you make it span on a single line? `Ln: line number / Cn: column number / En: ...`
 - Could you add a setting `showLegen` which defaults to `true`? You just need to edit this file: https://github.com/Duhemm/sbt-errors-summary/blob/master/src/main/contraband/ReporterConfig.contra. After editing, running `compile` in sbt will regenerate the code. (This PR shows how to add a setting: #28)

2017-07-23 08:21 UTC, Duhemm commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +          "%s%s^".format(" " * lineCol.length, sp)
`lineCol` also contains the formatting content, so it's length is longer than what's displayed:

```scala
scala> import scala.Console._
import scala.Console._

scala> val s = RED + "foo" + RESET
s: String = foo

scala> s.length
res0: Int = 12
```

I think that the best solution would be to use `prefixed` and use `lineCol` as prefix. This way, you don't need to worry about alignment.

2017-07-23 08:21 UTC, Duhemm commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +    logger.info("En: error number n")
What do you think of having a second line that shows the different meanings of the colors? (Simply showing error with the colour for errors, warning with the color for warnings, etc.)

2017-07-23 08:21 UTC, Duhemm commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +          })
Any reason to prefer `format` over string interpolation? I would prefer to keep string interpolation if you don't mind.

2017-07-23 08:21 UTC, Duhemm commented on src/test/scala/sbt/errorssummary/BasicConciseReporterSpec.scala
> +      messages should have length 2
`messages` contains all the lines of output. No that you display the legend, it should be longer.

2017-07-23 20:04 UTC, yawaramin commented on src/main/contraband-scala/sbt/errorssummary/ReporterConfig.scala
>  }
Yup, it's the default generated code without IDE or Scalafmt formatting. I have IDEA set up with a plugin to run Scalafmt only on files that I edit. I'll reformat to match what you have.

2017-07-23 20:08 UTC, yawaramin commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +    logger.info("En: error number n")
Sure, I can make the legend a single line and add a setting. If you don't mind, perhaps we can design the enhanced (coloured) legend as a future issue/PR?

2017-07-23 20:08 UTC, yawaramin commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +          })
I find format strings a bit easier to understand, but no worries, I can switch to interpolation.

2017-07-23 20:09 UTC, yawaramin commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +          "%s%s^".format(" " * lineCol.length, sp)
Ah, good point, and excellent suggestion. Will do.

2017-07-23 20:09 UTC, yawaramin commented on src/test/scala/sbt/errorssummary/BasicConciseReporterSpec.scala
> +      messages should have length 2
Oops, will make the change.

2017-07-23 20:39 UTC, yawaramin commented on src/test/scala/sbt/errorssummary/BasicConciseReporterSpec.scala
> +      messages should have length 2
Btw, it seems that all the tests are checking for `messages` length. Perhaps it's better for only one test (or one set of tests) to do the length checking?

2017-07-23 22:29 UTC, yawaramin commented
OK, I believe that covers all the points except the coloured legend.

2017-07-24 08:44 UTC, Duhemm commented on src/main/scala/sbt/errorssummary/ConciseReporter.scala
> +    logger.info("En: error number n")
Sure, no problem.

2017-07-24 09:06 UTC, Duhemm approved these changes
LGTM, thanks you very much!
I'll release that later today.

2017-07-24 09:06 UTC, merged

2017-08-08 08:04 UTC, olafurpg commented
Thank you @yawaramin for this addition, I love seeing the line numbers on the left of the code!